# Generated by Django 6.0.7 on 2026-07-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Subjects this teacher is assigned to (teachers only)', related_name='assigned_teachers', to='subjects.subject'),
        ),
    ]
