# Generated by Django 6.0.7 on 2026-07-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_super_admin_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('schools', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='user_role_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['school'], name='user_school_idx'),
        ),
    ]
