# Generated by Django 6.0.7 on 2026-07-16 22:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_question_search_idx'),
        ('schools', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='question_type_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty'], name='question_difficulty_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['status'], name='question_status_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject'], name='question_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['school'], name='question_school_idx'),
        ),
    ]
