# Generated by Django 6.0.7 on 2026-07-18 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question_question_type_idx_and_more'),
        ('schools', '0002_classlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='class_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='schools.classlevel'),
        ),
    ]
