# Generated by Django 6.0.7 on 2026-07-16 22:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
        ('questions', '0003_question_question_search_idx'),
        ('schools', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exampaper',
            index=models.Index(fields=['status'], name='paper_status_idx'),
        ),
        migrations.AddIndex(
            model_name='exampaper',
            index=models.Index(fields=['subject'], name='paper_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='exampaper',
            index=models.Index(fields=['school'], name='paper_school_idx'),
        ),
        migrations.AddConstraint(
            model_name='exampaperquestion',
            constraint=models.UniqueConstraint(fields=('exam_paper', 'order'), name='unique_paper_question_order'),
        ),
    ]
