# Generated by Django 6.0.7 on 2026-07-18 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_exampaper_paper_status_idx_and_more'),
        ('schools', '0002_classlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='class_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_papers', to='schools.classlevel'),
        ),
    ]
