# Generated by Django 6.0.7 on 2026-07-18 20:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. JSS 1, SS 2', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Sort order within school')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_levels', to='schools.school')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('name', 'school')},
            },
        ),
    ]
